apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-prod
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is the prod-environment for lab-group-28 </h1>
    </html