apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apache-prod

commonLabels:
  app: httpd

resources:
- deployment-apache-prod.yml
- cm-apache-prod.yml
- cm-index-prod.yml