apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: config-dev
          configMap:
            name: httpd-config-dev
            items:
            - key: "httpd.conf"
              path: "httpd.conf"
        - name: index-dev
          configMap:
            name: index-html-configmap-dev
            items:
            - key: "index.html"
              path: "index.html" 
      containers:
      - name: httpd
        image: httpd:latest
        volumeMounts:
          - name: config-dev
            mountPath: /usr/local/apache2/conf/
          - name: index-dev
            mountPath: /usr/local/apache2/htdocs/
        ports:
        - containerPort: 80