apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 30099
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: config
          configMap:
            name: httpd-config
            items:
            - key: "httpd.conf"
              path: "httpd.conf"
      containers:
      - name: httpd
        image: httpd:latest
        volumeMounts:
          - name: config
            mountPath: /usr/local/apache2/conf/
        ports:
        - containerPort: 80
