apiVersion: v1
kind: Service
metadata:
  name: beet-service
spec:
  selector:
    app: beetroot
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetroot-deployment
  labels:
    app: beetroot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beetroot
  template:
    metadata:
      labels:
        app: beetroot
    spec:
      containers:
      - name: beetroot
        image: oeegel15/beetroot-exercise-02:latest
        ports:
        - containerPort: 8080