apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apache-beetroot

commonLabels:
  app: httpd
  app: beetroot

resources:
- apache-deployment.yml
- beetroot-deployment.yml
- httpd-conf-cm.yml